### ISSUE TITLE
"Does not work with Teensy or Teensy 2.0+" on arduino mega

### ISSUE THREAD

**Issue by N00TN00T** [PaulStoffregen/ILI9341_t3#56]
Hey,

When I try to upload my arduino sketch with your example "graphicstest", I get the following error:
"Sorry, ILI9341_t3 does not work with Teensy 2.0 or Teensy++ 2.0.  Use Adafruit_ILI9341."
I don't really know what Teensy is, but from a quick google search it seems it's some form of board that I don't have. I have a mega 2560 arduino board.

**Comment by PaulStoffregen** [comment]
This library only works on Teensy 3.x and 4.x.  It will not run on Mega.

Use Adafruit_ILI9341, as the message says.
