### ISSUE TITLE
Unable to get display working

### ISSUE THREAD

**Issue by FriedCircuits** [PaulStoffregen/ILI9341_t3#6]
Hi,

I spent a few hours yesterday trying to get this library to work wit a 2.2in ili9341 display. Same pinout as the docs page has. I used the graphictest sketch. I tried with both standard and alt pins with and without the audio shield. Triple checked connections which worked with another micro. Then I tried the original Adafruit library and it worked fine with the same code. 

Only changes from standard graphictest sketch are below, each in their respective places. 

#define TFT_DC 20
#define TFT_CS 21

Adafruit_ILI9341 tft = Adafruit_ILI9341(TFT_CS, TFT_DC, 8);

 SPI.setMOSI(7);
 SPI.setSCK(14);

I haven't looked at the differences in the libraries to see if I can spot it yet. 

Thanks.

**Comment by PaulStoffregen** [comment]
The documentation has been updated.

http://www.pjrc.com/store/display_ili9341.html
http://www.pjrc.com/store/display_ili9341_touch.html

ILI9341_t3 requires using the 6-input constructor for alternate pinouts.

    // For optimized ILI9341_t3 library
    #define TFT_DC      20
    #define TFT_CS      21
    #define TFT_RST    255  // 255 = unused, connect to 3.3V
    #define TFT_MOSI     7
    #define TFT_SCLK    14
    #define TFT_MISO    12
    ILI9341_t3 tft = ILI9341_t3(TFT_CS, TFT_DC, TFT_RST, TFT_MOSI, TFT_SCLK, TFT_MISO);
