### ISSUE TITLE
swap clashes with c++ header <functional>

### ISSUE THREAD

**Issue by luni64** [PaulStoffregen/ILI9341_t3#62]
```c++
#include "ILI9341_t3.h"
#include <functional>

void setup()
{
}

void loop()
{
}
```
Does not compile. However, including `<functional>` before the ILI header works. 

The problem is the definition of the swap macro in ILI9341_t3.h which clashes with some definitions in `<functional>` (and possibly other standard c++ headers) 

https://github.com/PaulStoffregen/ILI9341_t3/blob/ff4bba3e1500ac3a025e391f0cb7de84ad95e1ee/ILI9341_t3.h#L555-L559

Since the macro is not used in the header you might consider moving its definition to the cpp file to avoid name clashes with other headers. 

Also see: https://forum.pjrc.com/threads/59112-TeensyTimerTool?p=246670&viewfull=1#post246670

**Comment by PaulStoffregen** [comment]
fixed by Kurt's PR
