### ISSUE TITLE
undeclared variable KINETISK_SPI0 compiling for UNO

### ISSUE THREAD

**Issue by bavareze** [PaulStoffregen/ILI9341_t3#64]
compiling the examples provided with the library using arduino studio for arduino uno r3

Arduino: 1.8.13 (Windows 7), Board: "Arduino Uno".  Looks like some undeclared variables.

Am I doing it wrong?

In file included from C:\Users\radu\Documents\Arduino\libraries\ILI9341_t3\examples\spitftbitmap\spitftbitmap.ino:17:0:

C:\Users\radu\Documents\Arduino\libraries\ILI9341_t3/ILI9341_t3.h: In member function 'void ILI9341_t3::waitFifoNotFull()':

C:\Users\radu\Documents\Arduino\libraries\ILI9341_t3/ILI9341_t3.h:178:9: error: 'KINETISK_SPI0' was not declared in this scope

    sr = KINETISK_SPI0.SR;

         ^~~~~~~~~~~~~

C:\Users\radu\Documents\Arduino\libraries\ILI9341_t3/ILI9341_t3.h: In member function 'void ILI9341_t3::waitFifoEmpty()':

C:\Users\radu\Documents\Arduino\libraries\ILI9341_t3/ILI9341_t3.h:187:9: error: 'KINETISK_SPI0' was not declared in this scope

    sr = KINETISK_SPI0.SR;

         ^~~~~~~~~~~~~

C:\Users\radu\Documents\Arduino\libraries\ILI9341_t3/ILI9341_t3.h: In member function 'void ILI9341_t3::waitTransmitComplete()':

C:\Users\radu\Documents\Arduino\libraries\ILI9341_t3/ILI9341_t3.h:193:12: error: 'KINETISK_SPI0' was not declared in this scope

   while (!(KINETISK_SPI0.SR & SPI_SR_TCF)) ; // wait until final output done

            ^~~~~~~~~~~~~

C:\Users\radu\Documents\Arduino\libraries\ILI9341_t3/ILI9341_t3.h:193:31: error: 'SPI_SR_TCF' was not declared in this scope

   while (!(KINETISK_SPI0.SR & SPI_SR_TCF)) ; // wait until final output done

                               ^~~~~~~~~~

C:\Users\radu\Documents\Arduino\libraries\ILI9341_t3/ILI9341_t3.h:194:9: error: 'KINETISK_SPI0' was not declared in this scope

   tmp = KINETISK_SPI0.POPR;                  // drain the final RX FIFO word

         ^~~~~~~~~~~~~

C:\Users\radu\Documents\Arduino\libraries\ILI9341_t3/ILI9341_t3.h: In member function 'void ILI9341_t3::writecommand_cont(uint8_t)':

C:\Users\radu\Documents\Arduino\libraries\ILI9341_t3/ILI9341_t3.h:197:3: error: 'KINETISK_SPI0' was not declared in this scope

   KINETISK_SPI0.PUSHR = c | (pcs_command << 16) | SPI_PUSHR_CTAS(0) | SPI_PUSHR_CONT;

   ^~~~~~~~~~~~~

C:\Users\radu\Documents\Arduino\libraries\ILI9341_t3/ILI9341_t3.h:197:51: error: 'SPI_PUSHR_CTAS' was not declared in this scope

   KINETISK_SPI0.PUSHR = c | (pcs_command << 16) | SPI_PUSHR_CTAS(0) | SPI_PUSHR_CONT;

                                                   ^~~~~~~~~~~~~~

C:\Users\radu\Documents\Arduino\libraries\ILI9341_t3/ILI9341_t3.h:197:71: error: 'SPI_PUSHR_CONT' was not declared in this scope

   KINETISK_SPI0.PUSHR = c | (pcs_command << 16) | SPI_PUSHR_CTAS(0) | SPI_PUSHR_CONT;

                                                                       ^~~~~~~~~~~~~~

C:\Users\radu\Documents\Arduino\libraries\ILI9341_t3/ILI9341_t3.h: In member function 'void ILI9341_t3::writedata8_cont(uint8_t)':

C:\Users\radu\Documents\Arduino\libraries\ILI9341_t3/ILI9341_t3.h:201:3: error: 'KINETISK_SPI0' was not declared in this scope

   KINETISK_SPI0.PUSHR = c | (pcs_data << 16) | SPI_PUSHR_CTAS(0) | SPI_PUSHR_CONT;

   ^~~~~~~~~~~~~

C:\Users\radu\Documents\Arduino\libraries\ILI9341_t3/ILI9341_t3.h:201:48: error: 'SPI_PUSHR_CTAS' was not declared in this scope

   KINETISK_SPI0.PUSHR = c | (pcs_data << 16) | SPI_PUSHR_CTAS(0) | SPI_PUSHR_CONT;

                                                ^~~~~~~~~~~~~~

C:\Users\radu\Documents\Arduino\libraries\ILI9341_t3/ILI9341_t3.h:201:68: error: 'SPI_PUSHR_CONT' was not declared in this scope

   KINETISK_SPI0.PUSHR = c | (pcs_data << 16) | SPI_PUSHR_CTAS(0) | SPI_PUSHR_CONT;

                                                                    ^~~~~~~~~~~~~~

C:\Users\radu\Documents\Arduino\libraries\ILI9341_t3/ILI9341_t3.h: In member function 'void ILI9341_t3::writedata16_cont(uint16_t)':

C:\Users\radu\Documents\Arduino\libraries\ILI9341_t3/ILI9341_t3.h:205:3: error: 'KINETISK_SPI0' was not declared in this scope

   KINETISK_SPI0.PUSHR = d | (pcs_data << 16) | SPI_PUSHR_CTAS(1) | SPI_PUSHR_CONT;

   ^~~~~~~~~~~~~

C:\Users\radu\Documents\Arduino\libraries\ILI9341_t3/ILI9341_t3.h:205:48: error: 'SPI_PUSHR_CTAS' was not declared in this scope

   KINETISK_SPI0.PUSHR = d | (pcs_data << 16) | SPI_PUSHR_CTAS(1) | SPI_PUSHR_CONT;

                                                ^~~~~~~~~~~~~~

C:\Users\radu\Documents\Arduino\libraries\ILI9341_t3/ILI9341_t3.h:205:68: error: 'SPI_PUSHR_CONT' was not declared in this scope

   KINETISK_SPI0.PUSHR = d | (pcs_data << 16) | SPI_PUSHR_CTAS(1) | SPI_PUSHR_CONT;

                                                                    ^~~~~~~~~~~~~~

C:\Users\radu\Documents\Arduino\libraries\ILI9341_t3/ILI9341_t3.h: In member function 'void ILI9341_t3::writecommand_last(uint8_t)':

C:\Users\radu\Documents\Arduino\libraries\ILI9341_t3/ILI9341_t3.h:210:3: error: 'KINETISK_SPI0' was not declared in this scope

   KINETISK_SPI0.SR = SPI_SR_TCF;

   ^~~~~~~~~~~~~

C:\Users\radu\Documents\Arduino\libraries\ILI9341_t3/ILI9341_t3.h:210:22: error: 'SPI_SR_TCF' was not declared in this scope

   KINETISK_SPI0.SR = SPI_SR_TCF;

                      ^~~~~~~~~~

C:\Users\radu\Documents\Arduino\libraries\ILI9341_t3/ILI9341_t3.h:211:51: error: 'SPI_PUSHR_CTAS' was not declared in this scope

   KINETISK_SPI0.PUSHR = c | (pcs_command << 16) | SPI_PUSHR_CTAS(0);

                                                   ^~~~~~~~~~~~~~

C:\Users\radu\Documents\Arduino\libraries\ILI9341_t3/ILI9341_t3.h: In member function 'void ILI9341_t3::writedata8_last(uint8_t)':

C:\Users\radu\Documents\Arduino\libraries\ILI9341_t3/ILI9341_t3.h:216:3: error: 'KINETISK_SPI0' was not declared in this scope

   KINETISK_SPI0.SR = SPI_SR_TCF;

   ^~~~~~~~~~~~~

C:\Users\radu\Documents\Arduino\libraries\ILI9341_t3/ILI9341_t3.h:216:22: error: 'SPI_SR_TCF' was not declared in this scope

   KINETISK_SPI0.SR = SPI_SR_TCF;

                      ^~~~~~~~~~

C:\Users\radu\Documents\Arduino\libraries\ILI9341_t3/ILI9341_t3.h:217:48: error: 'SPI_PUSHR_CTAS' was not declared in this scope

   KINETISK_SPI0.PUSHR = c | (pcs_data << 16) | SPI_PUSHR_CTAS(0);

                                                ^~~~~~~~~~~~~~

C:\Users\radu\Documents\Arduino\libraries\ILI9341_t3/ILI9341_t3.h: In member function 'void ILI9341_t3::writedata16_last(uint16_t)':

C:\Users\radu\Documents\Arduino\libraries\ILI9341_t3/ILI9341_t3.h:222:3: error: 'KINETISK_SPI0' was not declared in this scope

   KINETISK_SPI0.SR = SPI_SR_TCF;

   ^~~~~~~~~~~~~

C:\Users\radu\Documents\Arduino\libraries\ILI9341_t3/ILI9341_t3.h:222:22: error: 'SPI_SR_TCF' was not declared in this scope

   KINETISK_SPI0.SR = SPI_SR_TCF;

                      ^~~~~~~~~~

C:\Users\radu\Documents\Arduino\libraries\ILI9341_t3/ILI9341_t3.h:223:48: error: 'SPI_PUSHR_CTAS' was not declared in this scope

   KINETISK_SPI0.PUSHR = d | (pcs_data << 16) | SPI_PUSHR_CTAS(1);

                                                ^~~~~~~~~~~~~~

exit status 1

Error compiling for board Arduino Uno.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by PaulStoffregen** [comment]
This library is only for Teensy.  It is not for Arduino Uno.
